### ISSUE TITLE
[Feature Request] Detail Armor Bar support.

### ISSUE THREAD

**Issue by Dekamir** [Autovw/AdvancedNetherite#13]
**Requested feature**
[Detail Armor Bar](https://github.com/RedLime/DetailArmorBar) support.

**Solution**
[DAB API](https://github.com/RedLime/DetailArmorBar/wiki/For-Developer-(API-Document))

**Example texture**
![armor_bar_advnetherite (2)](https://user-images.githubusercontent.com/28929300/151139772-0aed668f-f118-40c5-88cc-96f3a4a40b66.png)
_This is a simple and quick mockup, picked off of existing armor texture color palette. I can make more detailed ones when you want to implement, unless you want to make them yourself._

**Comment by Autovw** [comment]
I would love to implement support for this in a future update, but DAB doesn't seem to work properly with armor sets that have more than 20 armor points (all pieces combined).
![image](https://user-images.githubusercontent.com/68228006/152397170-b252a795-aee8-4657-949a-7f328980fe33.png)

I'm gonna look into DAB support once I'll have more time for it.

**Comment by Autovw** [comment]
Currently have support for DAB implemented in my development environment, if everything goes according to plan support will be included in version 1.11.0 (MC 1.16.5 and 1.18.2)
![image](https://user-images.githubusercontent.com/68228006/163793324-3cf70513-62cc-4148-a9c0-e865713245e2.png)

**Comment by Autovw** [comment]
Support for Detail Armor Bar has been implemented in version 1.11.0 (and 1.5.0 for Fabric).
Thanks for the suggestion, enjoy!
