### ISSUE TITLE
[Crash Report] dedicated server crash 1.18.1

### ISSUE THREAD

**Issue by ZEROX7** [Autovw/AdvancedNetherite#14]
crashes on dedicated server

**Logs**

[crash-2022-03-02_18.08.25-fml.txt](https://github.com/Autovw/AdvancedNetherite/files/8171460/crash-2022-03-02_18.08.25-fml.txt)

**Technical Information (please complete the following information):**
 ! Do not say 'latest', provide the actual version.
 - Minecraft-version: 1.18.1
 - Forge-version: 39.0.79
 - Mod-version: 1.10.1-1.18.1

**Comment by Autovw** [comment]
Thanks for reporting the issue, I'll try to fix it as soon as possible. Temporary fix would be to downgrade Advanced Netherite one version.

**Comment by Autovw** [comment]
Issue has been fixed in version 1.10.2, update to receive the fix.
