### ISSUE TITLE
1.19 release bug

### ISSUE THREAD

**Issue by Bard8880** [Autovw/AdvancedNetherite#19]
while crafting the new netherite ingots works, you cannot use them in a smithing table to upgrade your equipment

**Comment by Autovw** [comment]
Thanks for your report, I'll investigate the issue ASAP

**Comment by Autovw** [comment]
I have not been able to replicate the issue (also tested the Fabric version just to make sure). Everything seems to work fine for me, could you perhaps provide additional information such as screenshots and which recipes don't work for you?

**Comment by Autovw** [comment]
I'll be closing this issue for now. Feel free to re-open if things still don't work correctly, but please provide the additional information I mentioned in my previous message if so.

**Comment by KennethRhodes8213** [comment]
Also having this issue on 1.19.4 Forge [https://gyazo.com/cfaef2b91e09d56644643ba06b471b9e](https://gyazo.com/cfaef2b91e09d56644643ba06b471b9e) I can't place my sword in the smithing table.

**Comment by KennethRhodes8213** [comment]
Just found out its an issue with the snapshot datapacks, would be cool if there was added support for this but I'm sure you're going to fix it anyyways in 1.20.

**Comment by Autovw** [comment]
@KennethRhodes8213 The experimental 1.20 features are not yet supported by this mod.

Also, in the future please open a new issue for this as the current issue this was posted on is unrelated, making it more difficult to keep track of :)
