### ISSUE TITLE
Tools break other blocks which they aren't meant to quickly.

### ISSUE THREAD

**Issue by Quarkul** [Autovw/AdvancedNetherite#23]
**Describe the bug**
When using any of the tools in this mod including swords, axes, hoes, shovels and pickaxes they break all blocks faster than they should.

**Steps to reproduce the behavior:**
1. Get any of the items mentioned beforehand.
2. Mine any block.

**Expected behavior**
Use of items on blocks not meant to be broken by these tools results in the same breaking speed as with your fists.

**Technical Information:**
 - Minecraft-version: 1.18.2
 - Forge-version: 40.1.84
 - Mod-version: 1.14.0

**Additional context**
No other mods were used.

**Comment by Autovw** [comment]
Thanks for the report!
I will get this fixed asap.

In case you're interested why this happens:

In an attempt at making the tool breaking speed configurable in version 1.14.0 I made the speed values from the config apply to tools without providing some additional checks. Apparently I forgot to test this properly before release.
