### ISSUE TITLE
Images in description on Modrinth aren't loading due to indirect requests from cache service

### ISSUE THREAD

**Issue by James103** [Autovw/AdvancedNetherite#27]
**Describe the bug**
Modrinth is changing the URLs of the images in your description on the [Modrinth page for this mod](https://modrinth.com/mod/advanced-netherite).

This is what you have in the README:
https://github.com/Autovw/AdvancedNetherite/blob/e620d12ad47007eabd09572154aec43ddce34a76/README.md?plain=1#L1

Modrinth is changing the above URL to:
```markdown
![Banner](https://wsrv.nl/?url=https://i.postimg.cc/4dzJ9yxX/Advanced-Netherite-Banner-V13.png)
```
(notice the `https://wsrv.nl/?url=` being automatically prepended to the URL)

Then, when the browser attempts to load the new URL (with `https://wsrv.nl/?url=` prepended), it fails because `wsrv.nl`, an image caching service, returns this error:
```
{"status":"error","code":404,"message":"The hostname of the origin is unresolvable (DNS) or blocked by policy."}
```

This is repeated for all of the images in the README and Modrinth description, not just the banner image.

You will need to repost the images on `imgur.com` and change the images in the URLs so they point to `i.imgur.com/...` with the corresponding images if you want them to load for more players.

**To Reproduce**
1. Check the description for the mod on Modrinth.
2. Notice the images aren't loading.
3. Check the URLs to the images.
4. Notice they're in the format `https://wsrv.nl/?url=https://i.postimg.cc/...`
5. In a browser, manually remove `https://wsrv.nl/?url=` from the URL and URL-decode the rest (replace `%3A%2F%2F` with `://` and `%2F` with `/`).
6. Notice the URL now loads and points to a valid image.

**Expected behavior**
The images should load fine for most players.

**Technical Information (please complete the following information):**
 - Minecraft-version: 1.19.2
 - Forge-version: 43.2.6
 - Mod-version: 1.14.7

**Comment by Autovw** [comment]
Thanks for pointing this out, I will be looking into it.
