### ISSUE TITLE
Trims

### ISSUE THREAD

**Issue by SamuelUlep** [Autovw/AdvancedNetherite#32]
**Is your feature request related to a problem? Please describe.**
Trims are not applicable to `Advanced Netherite` armor.

**Describe the solution you'd like**
Have in mod support for trims

**Additional context**
![image](https://github.com/Autovw/AdvancedNetherite/assets/129558275/c84f447d-16ba-4951-9dd5-1c3c59c2a1a2)

**Comment by Autovw** [comment]
Support for armor trims has not yet been implemented. Each trim (and trim colour) requires a brand new texture and I simply haven't had the time and motivation to make these.

There definitely will be armor trim support in the future, but it might take a while before all these textures have been made.
