### ISSUE TITLE
Simplyswords Weapons integration

### ISSUE THREAD

**Issue by dev-Blaze** [Autovw/AdvancedNetherite#35]
add compatibility with mod Simplyswords - https://github.com/Sweenus/SimplySwords

add versions of advanced netherite for the different kinds of weapons. 

https://modrinth.com/mod/advanced-netherite

**Comment by Autovw** [comment]
Adding new weapons for other mods (such as Simply Swords) is not something I want to do in the base mod. Perhaps someone else could make an addon for this instead.

Thanks for the suggestion anyway!
