### ISSUE TITLE
Silk Touch Duplication 

### ISSUE THREAD

**Issue by Skydarix** [Autovw/AdvancedNetherite#37]
**Describe the bug**
Using silk touch on any or the advanced netherite pickaxes with their corresponding ore essentially will duplicate that resource, while it is nice to gain an extra diamond or emerald even when mining with silk touch, the behaviour still applied to player placed ores and not just the naturally generated

**To Reproduce**
1. Grab a Netherite-Diamond Pickaxe & Apply Silk Touch
2. Grab Respective Ore block to pickaxe level (Diamond in this case)
3. Place ore & mine
4. Repeat step 3 a couple times until both the ore & diamond drops

**Expected behavior/s**:
- Silk touch negates the extra drop chance from the ore
OR preferably
- The drop chance only applies to naturally generated ore (like how player placed leaves don't decay)

**Technical Information (please complete the following information):**
 - Minecraft-version: 1.20.1
 - ModLoader-version: Fabric loader 0.14.25 & Fabric API 0.91.0
 - Mod-version: 2.0.2
 - Modpack(if relevant): Prominence II (RPG) v2.6.5

**Additional context**
This applies to both the deepslate and stone variants for the ores.

**Comment by Autovw** [comment]
This issue has been fixed in v2.0.3. Thanks for reporting!
