### ISSUE TITLE
About the Detail Armor for Fabric

### ISSUE THREAD

**Issue by Alvaro2003j** [Autovw/AdvancedNetherite#38]
**Is your feature request related to an issue? Please describe.**
Your mod for fabric is very good, but when I use the detail armor for fabric, the texture doesn't appear in the armor bar when I use the armor from your mod

**Describe the solution you would like**
I would like to know how I can configure that please.

**Additional context**
![imagen](https://github.com/Autovw/AdvancedNetherite/assets/93229518/8d16ed11-d2c3-4f43-b5ed-bdc3de747a32)
![imagen](https://github.com/Autovw/AdvancedNetherite/assets/93229518/e1b0e711-949c-4fe7-b398-8a761b51e2d1)

**Comment by Autovw** [comment]
Support for Detail Armor Bar was removed during the porting process to 1.20+ because said mod was not yet available for these versions. I have added back support for the mod in a recent update.
