### ISSUE TITLE
Mining Amethyst Clusters Only Give 2 Shards

### ISSUE THREAD

**Issue by sanbokojin** [Autovw/AdvancedNetherite#40]
When using any of the new pickaxes on amethyst clusters they always drop 2 shards like it would if you use your fist. Tried each one and with fortune, every time it dropped 2 shards. Tried with vanilla pickaxes and fortune and they dropped more like they should. Done in version 2.0.3 in fabric 1.20.4. Sorry if this was already posted and I missed it

**Comment by Autovw** [comment]
Fixed in version 2.1.0. Thanks for reporting!
