### ISSUE TITLE
Netherite-Iron, Netherite-Gold, Netherite-Emerald, and Netherite-Diamond have incorrect durability values in the 1.20.6 release.

### ISSUE THREAD

**Issue by PMarr62** [Autovw/AdvancedNetherite#43]
**The issue**
In the Advanced Netherite release 2.1.0 for Fabric 1.20.6, all armor pieces from Netherite-Iron, all the way up to Netherite-Diamond, have incorrect amor durability values.

**To Reproduce**
Two courses to reproduce the behavior:

Course 1) You can take a piece of the armor from the creative inventory.
Press F3+ G to show advanced tooltips in-game.
Take a piece of any armor, ranging from the Netherite-Iron up to the Netherite-Diamond, and take damage with it in survival mode.
You will notice that it has a severely decreased durability count.
Each armor piece in the corresponding set has exactly the same durability points.

Netherite-Iron has 39 durability points, Netherite-Gold has 41 durability points, Netherite-Emerald has 43 durability points, and Netherite-Diamond has 47 durability points.

Course 2) You can also manually craft the armor, starting with diamond armor, then using a smithing template and netherite ingot, crafting netherite armor. 
Then, by crafting a Netherite-Iron ingot, combining the previously-crafted Netherite armor with a smithing template to receive the Netherite-Iron armor of choice.
Equip the armor and take damage with it. You will notice it has the aforementioned durability points above.

Shown below are the screenshots displaying the durability hitpoints.

**Screenshots**
![image](https://github.com/Autovw/AdvancedNetherite/assets/117673241/3e176296-bac8-40d7-aa70-8a8ba9d10846)
![image](https://github.com/Autovw/AdvancedNetherite/assets/117673241/a327a164-f789-447d-b6bc-fd72ad02c7a0)
![image](https://github.com/Autovw/AdvancedNetherite/assets/117673241/1b6eba29-0191-48d7-8a74-54e3c0591208)
![image](https://github.com/Autovw/AdvancedNetherite/assets/117673241/4c1cc172-c610-4590-8a23-d66bb41798d1)

**Technical Information**
Minecraft-version: 1.20.6
ModLoader-version: Fabric Loader 0.15.11 and Fabric API 0.98.0
Mod-version: 2.1.0

**Comment by Autovw** [comment]
Fixed in version 2.1.1. Thanks for reporting!
