### ISSUE TITLE
Unable to enchant Netherite-Iron+ armor in Survival mode

### ISSUE THREAD

**Issue by Landros23** [Autovw/AdvancedNetherite#45]
**Describe the bug**
Enchantments cannot be applied to any modded tier of netherite armor, either through enchantment table or anvil, in Survival mode.

**To Reproduce**
1. Obtain a piece of modded netherite armor (any tier).
2a. Go to an anvil, and place the piece of armor alongside an appropriate enchantment book.
3a. Combination shows as invalid.
2b. Go to an enchantment table, and place the piece of armor alongside lapis lazuli
3b. With 30 levels, all options highlight, BUT do not show any enchantments and are not clickable.

**Expected behavior**
Armor should be enchantable in both cases.

**Screenshots**
Anvil (book used is Unbreaking III):
![Screenshot from 2024-05-14 15-41-46](https://github.com/Autovw/AdvancedNetherite/assets/82192189/72aed191-4366-479d-8038-51a4d5e2ecd7)

Enchanting table (level 30 option is highlighted, but no tooltip nor clickable):
![Screenshot from 2024-05-14 15-42-44](https://github.com/Autovw/AdvancedNetherite/assets/82192189/008cd931-f25b-4bf0-b06f-8f8600875994)

**Technical Information (please complete the following information):**
 - Minecraft-version: 1.20.6
 - ModLoader-version: Fabric loader 0.15.10 and Fabric API 0.98.0
 - Mod-version: 2.1.1

**Comment by Autovw** [comment]
Fixed in version 2.1.2. Thanks for reporting!
