### ISSUE TITLE
Visual bug with Detail Armor Bar

### ISSUE THREAD

**Issue by JustArthur** [Autovw/AdvancedNetherite#49]
**Visual Bug with Detail Armor Bar**
The visual bug is visible with any armor from the mod, with or without enchantments, With or without a texture pack, the bug persists.
No mod conflict, I tested with only the Details Armor Bar, Advanced Netherite, and Fabric API mods.

**Images**
With full set of the Netherite-Iron Armor.
![Netherite-Iron_Armor_Full_Set](https://github.com/Autovw/AdvancedNetherite/assets/92596486/ecdbbf80-284d-405d-bd7b-866441cc64e4)

Without Netherite-Iron Boots.
![Netherite-Iron_Armor_Without_Netherite-Iron_Boots](https://github.com/Autovw/AdvancedNetherite/assets/92596486/68b32c24-4132-4d94-9664-01ecc10f6ffd)

**Without Detail Armor Bar, it works perfectly.**
![without_Detail_Armor_Bar](https://github.com/Autovw/AdvancedNetherite/assets/92596486/2368322a-4152-496c-a96e-39ed7a190c94)

**Versions**
 - Minecraft-version: 1.21
 - ModLoader-version: Fabric 0.15.11 (0.100.3+1.21)
 - Mod-version [Advanced Netherite] : fabric-2.1.5-mc1.21
 - Mod-version [Detail Armor Bar] : 2.6.3+1.21-fabric

**Comment by Autovw** [comment]
I've investigated the issue and it seems to be caused by Detail Armor Bar. I've [opened an issue](https://github.com/RedLime/DetailArmorBar/issues/55) to notify the author of the mod about it.

Leaving this issue open until the bug has been resolved.

**Comment by Autovw** [comment]
I have removed Detail Armor Bar support in v2.2.1. This should solve this issue for the time being. I'll look into adding back support when the issue on Detail Armor Bar's end has been fixed.
