### ISSUE TITLE
Pickaxe Ability to drop more ores is not working in 1.21

### ISSUE THREAD

**Issue by jangoergens** [Autovw/AdvancedNetherite#52]
**Describe the bug**
Destroying 32 diamond ores with the diamond netherite pickaxe results in 32 diamonds instead of a higher number.

**Expected behavior**
More drops, like 38 diamonds.

**Screenshots**

**Technical Information (please complete the following information):**
 - Minecraft-version: 1.21
 - ModLoader-version: Fabric 0.16.2
 - Mod-version: v2.1.6-1.21

**Comment by Autovw** [comment]
This feature is temporarily disabled in the Fabric version of the mod.
In short: there have been some changes in Minecraft/Fabric code that broke the pickaxe drops. It'll be back once I can figure out a way to to make it work again.

**Comment by jangoergens** [comment]
Alright, thanks for the info!

**Comment by Autovw** [comment]
Fixed in v2.2.0
