### ISSUE TITLE
Swords should maintain consistency with their corresponding armor

### ISSUE THREAD

**Issue by Aaamorak** [Autovw/AdvancedNetherite#58]
example: The Diamond Sword has the perks of the Emerald- and Gold Sword but lacks the perk of the Iron Sword
This would cause inconsistency if someone were to for example; enable all the perks for the the Diamond Armor

I suggest either merging Swords and Armors or adding a new config option for Sword perks

![image](https://github.com/user-attachments/assets/82d56bfd-6c8c-40c5-8429-733d9ad36499)

**Comment by Autovw** [comment]
I've added the Netherite-Iron Sword perk to the Netherite-Diamond Sword in v2.2.0. Thanks for the suggestion.
