### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by LonelySauce** [Autovw/AdvancedNetherite#6]
**Describe the bug**
In the most recent update to the mod, the recipe for Netherite-Iron ingots now requires Netherite-Iron ingots to make. How in the fu-

**To Reproduce**
1. Open JEI
2. View the recipe for Netherite-Iron Ingots

**Expected behavior**
It shouldn't require a Netherite-Iron ingot to make a Netherite-Iron ingot.

**Screenshots**
![2021-10-03_03 19 39](https://user-images.githubusercontent.com/23504262/135744416-48b324ea-4ea9-4245-a38a-f819b2b0dc26.png)

**Technical Information (please complete the following information):**
 - Minecraft-version: 1.17.1
 - Forge-version: 37.0.75
 - Mod-version: advancednetherite-1.8.0-1.17.1.jar

Also, here's some Grammar corrections for you to include in the next update because poor grammar makes people like me wanna lose our minds:

Change the "Pacifies Endermans" text to "Pacifies Endermen"
The text for everything involving a "/" in it needs to be swapped for a "-" because a slash is supposed to be used as a substitute for "or", not to unify two things into one thing. These aren't "Netherite or Iron ingots" they're "Netherite-Iron ingots" since you're unifying two materials together, same goes for every other item including tools and armor.

**Comment by Autovw** [comment]
Might be a good idea to start using data generators to prevent this from happening in the future.
Thank you for reporting this issue!

After having thought about it I have decided to use dashes instead of slashes, makes more sense indeed.
Thanks for the feedback, everything should be fixed in version 1.8.1.

**Comment by LonelySauce** [comment]
Thanks a bunch, glad you responded to this so quickly.
