### ISSUE TITLE
[Bug Report] Recipes are... out of order.

### ISSUE THREAD

**Issue by LonelySauce** [Autovw/AdvancedNetherite#7]
**Describe the bug**
The order for EVERY recipe broke.

**To Reproduce**
1. Open the recipes in JEI
2. Oh hey that's it, nice.

**Expected behavior**
Recipes shouldn't act like this.

**Screenshots**
![2021-10-03_16 53 24](https://user-images.githubusercontent.com/23504262/135771299-62ee5cfe-c90f-432a-93e9-c3aa1001de13.png)
![2021-10-03_16 54 23](https://user-images.githubusercontent.com/23504262/135771300-f79e5921-509e-44a1-9eb7-e1235214eeb5.png)
![2021-10-03_16 54 32](https://user-images.githubusercontent.com/23504262/135771301-a78c9409-8110-4d24-b914-7947b7acce25.png)

**Technical Information (please complete the following information):**
 - Minecraft-version: 1.17.1
 - Forge-version: 37.0.75
 - Mod-version: advancednetherite-1.8.1-1.17.1.jar

**Additional context**
This sucks.

**Comment by LonelySauce** [comment]
When Emerald+Emerald=Diamond lmao

**Comment by Autovw** [comment]
Woops....
Yeah I changed the way crafting recipes work in version 1.8.0, but while attempting to fix the issue I created more issues, I'm gonna try to get a fix out ASAP.
I'm sorry, should've tested this more before I released the update.

**Comment by Autovw** [comment]
Thanks for reporting, issue should be fixed now in version 1.8.2!
