### ISSUE TITLE
[Bug Report] Every advancement unlocks when picking up a random item

### ISSUE THREAD

**Issue by muffinkin** [Autovw/AdvancedNetherite#9]
**Describe the bug**
On any item pickup, all armor set achievements are automatically given.

**To Reproduce**
1. load into a new world
2. pickup any item

**Expected behavior**

**Technical Information**
 ! Do not say 'latest', provide the actual version.
 - Minecraft-version: 1.16.5
 - Forge-version: 36.2.19
 - Mod-version: 1.9.0

**Additional context**
I am running a modpack with many mods.

**Comment by LatiusAuro** [comment]
I don't know if this has been fixed as well, but the "Why?" challenge advancement also seems to auto-complete, at least when a starter kit is involved (which basically gives you items at the start of a new save)

**Comment by Autovw** [comment]
Correct, issue has already been fixed. I'm sorry the update with the fix is taking so long, but I'm currently reworking core parts of the mod, which needs to be done correctly.

**Comment by Autovw** [comment]
Fixed the issue in version 1.10.0.
Thanks for reporting.
